### ISSUE TITLE
学部紹介の修正箇所

### ISSUE THREAD

**Issue by daisukesaito42** [gsc-aoyama/www4gsc#7]
https://gsc-aoyama.github.io/www4gsc/introduction/outline/
- [x] ①多角的な視点もって→多角的な視点をもって
https://github.com/gsc-aoyama/www4gsc/commit/dea4256fae160f0aaf0459634698e2c1bb47dfdd

- [x] ②人々が互いを尊重しあいながら生きる共生社会に近づくことができるのではないでしょうか。 （改行入れる）地球社会共生学部。
https://github.com/gsc-aoyama/www4gsc/commit/2175a83db1e94b53df99ae3e0a0ed7bc33df392f

- [x] ③ダイナミックに変貌するグローバル社会では、あらゆる「境堺（ボーダー）」を越える新たな「つながり」が生まれています。（改行）

グローバルな人の流れ、自在に展開するメディアや文化。このような「つながり」は世界の光景を一変させ、新たな可能性を生み出す一方で、グローバルな規模でさまざまな課題を顕在化させています。（改行）

 環境問題や紛争、経済や情報の格差。世界的な問題でありつつ、私たちの日常にも影響を及ぼすこのような問題を理解し、要因をさぐり、解決策を見出していくには、何が必要なのでしょうか。（改行）

地球社会共生学部では、経済学・経営学、政治学、社会学、メディア・空間情報学の４つの領域を複合させた学びを提供し、専門的な学問分野の垣根を越えて学際的に学ぶことで、多様な視点から私たちが生きる複雑な社会の姿をとらえる力をつけていきます。

https://github.com/gsc-aoyama/www4gsc/commit/36fe168e9624db5e9e287df654b6b1765f4c0476

**Comment by mapconcierge** [comment]
修正しました！
https://gsc-aoyama.github.io/www4gsc/introduction/outline/

<img width="789" alt="2018-06-27 18 24 59" src="https://user-images.githubusercontent.com/416977/41965560-cc9da310-7a37-11e8-8b8a-5a9fcdd46738.png">

**Comment by mapconcierge** [comment]
閉じます！

**Comment by daisukesaito42** [comment]
ありがとうございます！
